stages:
  - build
  - test

build_nodejs_app:
  stage: build
  image: node:lts-alpine
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

test_nodejs_app:
  stage: test
  image: node:lts-alpine
  script:
    - npm install
    - npm run test