image: node:20-bullseye

cache:
  paths:
    - node_modules/

stages:
  - build

build:
  stage: build
  tags:
    - docker
  before_script:
    - npm install -g @angular/cli@11.2.19

  script:
    - npm ci --legacy-peer-deps
    - npm run build
